## a)ImportData,head,tail,describe,shape&dtypes

In [152]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as st
%matplotlib inline
 
import scipy.stats as st    
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, RandomForestRegressor, GradientBoostingRegressor
from sklearn.neural_network import MLPClassifier,MLPRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.svm import SVC,SVR
from sklearn.metrics import confusion_matrix

In [2]:
df=pd.read_csv("Datasets BITS/Data Set for Classification.csv")

In [3]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

           ...           PerformanceRating RelationshipSatisfaction  \
0          ...                           3                        1   
1          ...                           4                        4   
2          ...                           3                        2   
3          ...                           3                        3   
4          ...                           3                        4   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                  8                      0               1   
1                 1                 10                      3               3   
2                 0                  7                      3               3   
3                 0                  8                      3               3   
4                 1                  6                      3               3   

   YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                  4                        0   
1              10                  7                        1   
2               0                  0                        0   
3               8                  7                        3   
4               2                  2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 33 columns]

In [4]:
df.tail()

Age Attrition     BusinessTravel  DailyRate              Department  \
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber          ...           PerformanceRating  \
1465            2061          ...                           3   
1466            2062          ...                           3   
1467            2064          ...                           4   
1468            2065          ...                           3   
1469            2068          ...                           3   

     RelationshipSatisfaction  StockOptionLevel  TotalWorkingYears  \
1465                        3                 1                 17   
1466                        1                 1                  9   
1467                        2                 1                  6   
1468                        4                 0                 17   
1469                        1                 0                  6   

      TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
1465                      3               3               5   
1466                      5               3               7   
1467                      0               3               6   
1468                      3               2               9   
1469                      3               4               4   

     YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
1465                  2                        0                     3  
1466                  7                        1                     7  
1467                  2                        0                     3  
1468                  6                        0                     8  
1469                  3                        1                     2  

[5 rows x 33 columns]

In [5]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel          ...           PerformanceRating  \
count  1470.000000          ...                 1470.000000   
mean      2.063946          ...                    3.153741   
std       1.106940          ...                    0.360824   
min       1.000000          ...                    3.000000   
25%       1.000000          ...                    3.000000   
50%       2.000000          ...                    3.000000   
75%       3.000000          ...                    3.000000   
max       5.000000          ...                    4.000000   

       RelationshipSatisfaction  StockOptionLevel  TotalWorkingYears  \
count               1470.000000       1470.000000        1470.000000   
mean                   2.712245          0.793878          11.279592   
std                    1.081209          0.852077           7.780782   
min                    1.000000          0.000000           0.000000   
25%                    2.000000          0.000000           6.000000   
50%                    3.000000          1.000000          10.000000   
75%                    4.000000          1.000000          15.000000   
max                    4.000000          3.000000          40.000000   

       TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  \
count            1470.000000      1470.000000     1470.000000   
mean                2.799320         2.761224        7.008163   
std                 1.289271         0.706476        6.126525   
min                 0.000000         1.000000        0.000000   
25%                 2.000000         2.000000        3.000000   
50%                 3.000000         3.000000        5.000000   
75%                 3.000000         3.000000        9.000000   
max                 6.000000         4.000000       40.000000   

       YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
count         1470.000000              1470.000000           1470.000000  
mean             4.229252                 2.187755              4.123129  
std              3.623137                 3.222430              3.568136  
min              0.000000                 0.000000              0.000000  
25%              2.000000                 0.000000              2.000000  
50%              3.000000                 1.000000              3.000000  
75%              7.000000                 3.000000              7.000000  
max             18.000000                15.000000             17.000000  

[8 rows x 25 columns]

In [6]:
df.shape

(1470, 33)

In [7]:
df.YearsInCurrentRole.value_counts().sort_values()

18      2
17      4
16      7
15      8
12     10
14     11
13     14
11     22
10     29
5      36
6      37
1      57
9      67
8      89
4     104
3     135
7     222
0     244
2     372
Name: YearsInCurrentRole, dtype: int64

In [8]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance     

## Hypothesis Testing

### 1) Gender vs Attrition


NULL Hypothesis : there is no relation between Gender and Attrition<br/> 
ALTERNATE Hypothesis: there is relation between Gender and Attrition

In [9]:
pd.crosstab(df.Gender, df.Attrition)

Attrition   No  Yes
Gender             
Female     501   87
Male       732  150

In [10]:
st.chi2_contingency(pd.crosstab(df.Gender, df.Attrition))

(1.1169671241970975, 0.29057244902890855, 1, array([[493.2,  94.8],
        [739.8, 142.2]]))

### since the p value is greater than 0.05 Accept the NULL Hypothesis i.e.. there is no relation between gender and attrition

## 2) EducationFieldvsAttrition

NULL Hypothesis : there is no relation between EducationField and Attrition<br/>
ALTERNATE Hypothesis: there is relation between EducationField and Attrition

In [11]:
pd.crosstab(df.EducationField, df.Attrition)

Attrition          No  Yes
EducationField            
Human Resources    20    7
Life Sciences     517   89
Marketing         124   35
Medical           401   63
Other              71   11
Technical Degree  100   32

In [12]:
st.chi2_contingency(pd.crosstab(df.EducationField, df.Attrition))

(16.024674119585427,
 0.006773980139025212,
 5,
 array([[ 22.64693878,   4.35306122],
        [508.29795918,  97.70204082],
        [133.36530612,  25.63469388],
        [389.19183673,  74.80816327],
        [ 68.77959184,  13.22040816],
        [110.71836735,  21.28163265]]))

### since the p value is less than 0.05 REJECT the NULL Hypothesis i.e.. there is relation between EducationField and attrition

## 3) GendervsMonthlyIncome
Null Hypothesis: there is no significant difference in the avg monthly income of male & female - both means are equal<br/>
Alternate Hypothesis : there is significant difference in avg. monthly income of male & female - both means are not equal

In [13]:
df.MonthlyIncome.groupby(df.Gender).mean()

Gender
Female    6686.566327
Male      6380.507937
Name: MonthlyIncome, dtype: float64

In [14]:
male=df[df.Gender=='Male']
female=df[df.Gender=='Female']

In [15]:
st.ttest_ind(male.MonthlyIncome,female.MonthlyIncome)

Ttest_indResult(statistic=-1.2212617308870655, pvalue=0.22218303455087898)

### since the p value is greater than 0.05 Accept the NULL Hypothesis i.e..,  there is no significant difference in the avg monthly income of male & female. the difference of 306$ doesn't matter

## 4)MaritalStatusvsMonthlyIncome
Null Hypothesis: there is no significant difference in the avg monthly income of married, unmarried & divorced - both means are equal<br/>
Alternate Hypothesis : there is significant difference in avg. monthly income of married, unmarried & divorced - both means are not equal

In [16]:
df.MonthlyIncome.groupby(df.MaritalStatus).mean()

MaritalStatus
Divorced    6786.287462
Married     6793.671620
Single      5889.472340
Name: MonthlyIncome, dtype: float64

In [17]:
married=df[df.MaritalStatus=='Married']
single=df[df.MaritalStatus=='Single']
divorced=df[df.MaritalStatus=='Divorced']

In [18]:
st.f_oneway(married.MonthlyIncome,single.MonthlyIncome,divorced.MonthlyIncome)

F_onewayResult(statistic=5.904753323759054, pvalue=0.002791675956684596)

### since p value is less than 0.05 REJECT null hypothesis that the avg. monthly income of married, unmarried & divorced is equal. the difference is statistically significant

## 5) DistancefromHomevsAttrition
NULL Hypothesis : there is no relation between Distance from home and Attrition<br/>
ALTERNATE Hypothesis: there is relation between Distance from home and Attrition

In [19]:
pd.crosstab(df.DistanceFromHome,df.Attrition)

Attrition          No  Yes
DistanceFromHome          
1                 182   26
2                 183   28
3                  70   14
4                  55    9
5                  55   10
6                  52    7
7                  73   11
8                  70   10
9                  67   18
10                 75   11
11                 25    4
12                 14    6
13                 13    6
14                 17    4
15                 21    5
16                 25    7
17                 15    5
18                 22    4
19                 19    3
20                 21    4
21                 15    3
22                 13    6
23                 22    5
24                 16   12
25                 19    6
26                 22    3
27                  9    3
28                 21    2
29                 22    5

In [20]:
st.chi2_contingency(pd.crosstab(df.DistanceFromHome,df.Attrition))

(38.16850025507776,
 0.09525313501707136,
 28,
 array([[174.46530612,  33.53469388],
        [176.98163265,  34.01836735],
        [ 70.45714286,  13.54285714],
        [ 53.68163265,  10.31836735],
        [ 54.52040816,  10.47959184],
        [ 49.4877551 ,   9.5122449 ],
        [ 70.45714286,  13.54285714],
        [ 67.10204082,  12.89795918],
        [ 71.29591837,  13.70408163],
        [ 72.13469388,  13.86530612],
        [ 24.3244898 ,   4.6755102 ],
        [ 16.7755102 ,   3.2244898 ],
        [ 15.93673469,   3.06326531],
        [ 17.61428571,   3.38571429],
        [ 21.80816327,   4.19183673],
        [ 26.84081633,   5.15918367],
        [ 16.7755102 ,   3.2244898 ],
        [ 21.80816327,   4.19183673],
        [ 18.45306122,   3.54693878],
        [ 20.96938776,   4.03061224],
        [ 15.09795918,   2.90204082],
        [ 15.93673469,   3.06326531],
        [ 22.64693878,   4.35306122],
        [ 23.48571429,   4.51428571],
        [ 20.96938776,   4.03061224],
   

### since the p value is greater than 0.05 Accept the NULL Hypothesis i.e.. there is no relation between Distance from home and attrition

## 6)GendervsYearsatCurrentrole
NULL Hypothesis : there is no relation between Gender and YearsinCurrentrole<br/>
ALTERNATE Hypothesis: there is relation between Gender and YearsinCurrentrole

In [21]:
pd.crosstab(df.Gender,df.YearsInCurrentRole)

YearsInCurrentRole   0   1    2   3   4   5   6    7   8   9   10  11  12  13  \
Gender                                                                          
Female               89  24  147  53  44  15  17   95  31  20   8  13   6   8   
Male                155  33  225  82  60  21  20  127  58  47  21   9   4   6   

YearsInCurrentRole  14  15  16  17  18  
Gender                                  
Female               7   4   4   3   0  
Male                 4   4   3   1   2

In [22]:
st.chi2_contingency(pd.crosstab(df.YearsInCurrentRole,df.Gender))

(22.55061951716324, 0.2084536425366629, 18, array([[ 97.6, 146.4],
        [ 22.8,  34.2],
        [148.8, 223.2],
        [ 54. ,  81. ],
        [ 41.6,  62.4],
        [ 14.4,  21.6],
        [ 14.8,  22.2],
        [ 88.8, 133.2],
        [ 35.6,  53.4],
        [ 26.8,  40.2],
        [ 11.6,  17.4],
        [  8.8,  13.2],
        [  4. ,   6. ],
        [  5.6,   8.4],
        [  4.4,   6.6],
        [  3.2,   4.8],
        [  2.8,   4.2],
        [  1.6,   2.4],
        [  0.8,   1.2]]))

### since the p value is greater than 0.05 Accept the NULL Hypothesis i.e.., there is no relation between Gender and YearsinCurrentrole

## 7)MaritalStatusvsYearsatCurrentrole
NULL Hypothesis : there is no relation between MaritalStatus and YearsinCurrentrole<br/>
ALTERNATE Hypothesis: there is relation between MaritalStatus and YearsinCurrentrole

In [23]:
pd.crosstab(df.MaritalStatus,df.YearsInCurrentRole)

YearsInCurrentRole  0   1    2   3   4   5   6   7   8   9   10  11  12  13  \
MaritalStatus                                                                 
Divorced            50  17   79  34  17   8   5  55  21  14   8   6   2   4   
Married             99  24  172  58  49  13  20  95  49  37  16  11   6   6   
Single              95  16  121  43  38  15  12  72  19  16   5   5   2   4   

YearsInCurrentRole  14  15  16  17  18  
MaritalStatus                           
Divorced             3   0   2   2   0  
Married              5   6   4   2   1  
Single               3   2   1   0   1

In [24]:
st.chi2_contingency(pd.crosstab(df.MaritalStatus,df.YearsInCurrentRole))

(36.0450733221542,
 0.4665396278640823,
 36,
 array([[ 54.27755102,  12.67959184,  82.75102041,  30.03061224,
          23.13469388,   8.00816327,   8.23061224,  49.38367347,
          19.79795918,  14.90408163,   6.45102041,   4.89387755,
           2.2244898 ,   3.11428571,   2.44693878,   1.77959184,
           1.55714286,   0.88979592,   0.44489796],
        [111.70884354,  26.09591837, 170.31020408,  61.80612245,
          47.61360544,  16.48163265,  16.93945578, 101.63673469,
          40.7462585 ,  30.67414966,  13.27687075,  10.07210884,
           4.57823129,   6.40952381,   5.03605442,   3.66258503,
           3.2047619 ,   1.83129252,   0.91564626],
        [ 78.01360544,  18.2244898 , 118.93877551,  43.16326531,
          33.25170068,  11.51020408,  11.82993197,  70.97959184,
          28.45578231,  21.42176871,   9.27210884,   7.03401361,
           3.19727891,   4.47619048,   3.5170068 ,   2.55782313,
           2.23809524,   1.27891156,   0.63945578]]))

### since the p value is greater than 0.05 Accept the NULL Hypothesis i.e..,  there is no relation between MaritalStatus and YearsinCurrentrole

## There is no missing(null) data in the given Dataset

In [25]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int

## Label Encoding

In [26]:
dfnum=df.select_dtypes(include=[np.number])
dfcat=df.select_dtypes(include=[object])

In [27]:
le=LabelEncoder()

In [28]:
dfcat1=dfcat.apply(le.fit_transform)

In [29]:
df2=pd.concat([dfnum,dfcat1],axis=1)

In [30]:
df2.head()

Age  DailyRate  DistanceFromHome  Education  EmployeeCount  EmployeeNumber  \
0   41       1102                 1          2              1               1   
1   49        279                 8          1              1               2   
2   37       1373                 2          2              1               4   
3   33       1392                 3          4              1               5   
4   27        591                 2          1              1               7   

   EnvironmentSatisfaction  HourlyRate  JobInvolvement  JobLevel    ...     \
0                        2          94               3         2    ...      
1                        3          61               2         2    ...      
2                        4          92               2         1    ...      
3                        4          56               3         1    ...      
4                        1          40               3         1    ...      

   YearsSinceLastPromotion  YearsWithCurrManager  Attrition  BusinessTravel  \
0                        0                     5          1               2   
1                        1                     7          0               1   
2                        0                     0          1               2   
3                        3                     0          0               1   
4                        2                     2          0               2   

   Department  EducationField  Gender  JobRole  MaritalStatus  OverTime  
0           2               1       0        7              2         1  
1           1               1       1        6              1         0  
2           1               4       1        2              2         1  
3           1               1       0        6              1         1  
4           1               3       1        2              1         0  

[5 rows x 33 columns]

## 1)BinaryLogisticRegression

In [41]:
X=df2.drop('Attrition',axis=1)
y=df2['Attrition']

In [42]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [43]:
lr= LogisticRegression()

In [44]:
lr1=lr.fit(X_train,y_train)

In [45]:
lr1.score(X_test,y_test)

0.8775510204081632

In [47]:
pd.crosstab(y_test,lr1.predict(X_test))

col_0        0  1
Attrition        
0          251  4
1           32  7

In [48]:
(251+7)/(251+4+32+7)

0.8775510204081632

## 2)DecisionTreeClassifier

In [49]:
dt= DecisionTreeClassifier()

In [50]:
dt1=dt.fit(X_train,y_train)
dt1.score(X_test,y_test)

0.7653061224489796

In [51]:
pd.crosstab(y_test,dt1.predict(X_test))

col_0        0   1
Attrition         
0          220  35
1           34   5

In [52]:
(220+5)/(220+35+34+5)

0.7653061224489796

## 3)RandomForestClassifier

In [72]:
rf=RandomForestClassifier(n_estimators=100)

In [73]:
rf1=rf.fit(X_train,y_train)
rf1.score(X_test,y_test)

0.8741496598639455

In [75]:
print(confusion_matrix(y_test,rf1.predict(X_test)))

[[253   2]
 [ 35   4]]


In [78]:
(253+4)/(253+2+35+4)

0.8741496598639455

## 4)GradientBoostingClassifier

In [79]:
gbm= GradientBoostingClassifier()

In [80]:
gbm1=gbm.fit(X_train,y_train)

In [81]:
gbm1.score(X_test,y_test)

0.8877551020408163

In [82]:
pd.crosstab(y_test,gbm1.predict(X_test))

col_0        0   1
Attrition         
0          248   7
1           26  13

In [83]:
(248+13)/(26+7+248+13)

0.8877551020408163

## 5) NeuralNetworkClassifier

In [126]:
nn= MLPClassifier()

In [127]:
nn1=nn.fit(X_train,y_train)

In [128]:
nn1.score(X_test,y_test)

0.8673469387755102

In [129]:
print(confusion_matrix(y_test,nn1.predict(X_test)))

[[255   0]
 [ 39   0]]


In [130]:
255/(255+39)

0.8673469387755102

## 6)SupportVectorMachineClassifier

In [135]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']} 

In [136]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [137]:
svm1=grid.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV]  C=0.1, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV]  C=0.1, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV]  C=0.1, gamma=0.1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV]  C=0.1, gamma=0.01, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=0.1, gamma=0.01, kernel=rbf .........

[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=100, gamma=0.0001, kernel=rbf .................................
[CV]  C=100, gamma=0.0001, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=1000, gamma=1, kernel=rbf .....................................
[CV]  C=1000, gamma=1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV]  C=1000, gamma=0.1, kernel=rbf, score=0.8316326530612245, total=   0.0s
[CV] C=1000, gamma=0.1, kernel=rbf 

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:   11.4s finished


In [140]:
grid.best_params_

{'C': 0.1, 'gamma': 1, 'kernel': 'rbf'}

In [142]:
grid.best_estimator_

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [144]:
grid.score(X_test,y_test)

0.8673469387755102

In [145]:
pd.crosstab(y_test,grid.predict(X_test))

col_0        0
Attrition     
0          255
1           39

In [146]:
print(confusion_matrix(y_test,svm1.predict(X_test)))

[[255   0]
 [ 39   0]]


In [97]:
255/(255+39)

0.8673469387755102

## 7)KNNClassifier

In [147]:
knn= KNeighborsClassifier()

In [148]:
knn1=knn.fit(X_train,y_train)

In [149]:
knn1.score(X_test,y_test)

0.8537414965986394

In [150]:
pd.crosstab(y_test,knn1.predict(X_test))

col_0        0  1
Attrition        
0          246  9
1           34  5

In [151]:
(246+5)/(246+9+5+34)

0.8537414965986394

# The Best Model is GradientBoostingClassifier


# The Worst Model is DecisionTreeClassifier